### ISSUE TITLE
Tools?

### ISSUE THREAD

**Issue by Fozar** [Mardoxx/skyrimui#10]
Hey.  I would like to know about the procedure of how these sources were created.  I really need the source of startmenu for SSE, what is the best way to do this? Thanks

**Comment by Scrivener07** [comment]
Use [JPEXS FFDec, the free flash decompiler](https://github.com/jindrapetrik/jpexs-decompiler/releases).
Open the SWF in the application and export it as an FLA or XFL. You will need Adobe Flash or Adobe Animate to make any meaningful changes. I see you asking for help on this topic in several discords and git repos. Share more about what your even trying to do. The [xSE Discord](https://discord.gg/ybWkUvb) is a good place to carry on this discussion.

Closing this here.
