### ISSUE TITLE
Corrupt FLA files

### ISSUE THREAD

**Issue by wesbeyrent** [Mardoxx/skyrimui#12]
This may be a version obsolescence issue, but Adobe Animate says all the .fla files are corrupt.

**Comment by Mardoxx** [comment]
You'll need Flash 8, I think it came in Adobe CS2?

I think I once got it working with CS5 but it had some weird quirks with
some of the embedded transparent gradients (pngs)

**Comment by wesbeyrent** [comment]
That solved it.  Thanks a million!  Working on porting this to the Switch with actual NX button art.
