### ISSUE TITLE
Can't find the information I am looking for. 

### ISSUE THREAD

**Issue by JimmyRaz** [Mardoxx/skyrimui#9]
I have looked through the source code thoroughly and have not been able to find these scripts and functions.

1. When the player uses a poison in the game, a message box stops the game and asks the player if they want to poison the weapon.  I want to disable that.  I can not find it anywhere in the game or in the UI.

2. I want to add 4 new hot keys.  Can not find the Hotkey Script or Function anywhere in the UI.

I have searched everywhere for information on the UI but have come up completely empty handed.  
Can you please give me some direction on how to find these functions or even the script properties?

Also,  If I decompile and recompile a Menu.swf and place it in an Archive, will it even work?  

Thank You for your time.

**Comment by Mardoxx** [comment]
1. You can't, without nasty hacks (string matching)  look at dialogue swf. I did it with an SKSE plugin, which bypassed the message box callback. It was pretty clean.

2. You won't find hotkey stuff in UI.

**Comment by JimmyRaz** [comment]
Thanks for your help.  Would there be any chance to change the message box
into just a message?  So it displayed but did to stop the game.

Is it an actual Message Box or a scripted box that they fill the properties
with?

**Comment by Mardoxx** [comment]
Yes that is possible as I did for the nopoisonsdialogue but not from Ui side. This was done as SKSE plugin

**Comment by JimmyRaz** [comment]
Thanks Mardoxx,

We do not have SKSE for SE. So without it, it can not be done?  You
probably just saved me several hours of time.

**Comment by Mardoxx** [comment]
No, not yet anyway!

**Comment by JimmyRaz** [comment]
As far as SKSE, I am staying clear of that because I think Bethesda is
going to be bringing back paid mods.  The big money there will be in XBox
and I suspect PlayStation will be removing their "No External Access" rules
also.

I suppose the Hotkeys can not be death with without SKSE either?

If you can think of a way to get your no potions Mod to work without SKSE
please let me know.

Thanks Again you saved me a lot of time.

**Comment by Mardoxx** [comment]
"As far as SKSE, I am staying clear of that because I think Bethesda is going to be bringing back paid mods. "

Not sure what you are getting at here

**Comment by JimmyRaz** [comment]
SKSE will most likely not work with consoles.  I want my mod to be full
compatible with them.  My mod is not a UI mod it is a game overhaul.  I
just wanted to make those changes to the UI for the Mod.  Of course it
would also be useful for the Vanilla game also.

**Comment by Mardoxx** [comment]
Right and you thought you'd piggyback of my work to make money?

**Comment by JimmyRaz** [comment]
What?? Of course not.  Why would I have mentioned that if I was attempting
to do that. If you contributed to the Mod and paid Mods where not tried
again. I would give you full credit.  If they were you would certainly be
entitled to some compensation.

**Comment by Mardoxx** [comment]
Was just gonna say good luck to you :p

**Comment by JimmyRaz** [comment]
Please don't take this the wrong way, but you are little twat.:p

**Comment by Mardoxx** [comment]
I think we made well under $500 for SkyUI in donations over the past 6 years!

**Comment by JimmyRaz** [comment]
Mardoxx,

I have never used SkyUI.  I was just asking you for some very simple
information regarding the UI and you freak on me? I am not to blame for the
leach fest the Nexus and Steam created.

Now they are leaching up Mods on Bethesda.

This is what I waned to be able to do with the UI.

1. Get rid the Potion Message
2. Add 4 more hot keys - Total 12
3. Make everything in the game done in real time.  Meaning that going into
the Menu does not stop the game.

Does that sound like a copy of your work?  I hope not those are all
original ideas.

Thanks again for taking 5 Min of your time to save me several hours of
wasted time.  I have done the same for others.
